name: 'dbt-project'
version: '1.0'
config-version: 2

profile: 'dbt-project'

# Paths
model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]

# Build output
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dbt-project:
    +database: raw_analytics
    +schema: raw

    customer:
      +column_types:
        id: integer
        first_name: string
        last_name: string

    orders:
      +column_types:
        id: integer
        user_id: integer
        order_date: date
        status: string

    payments:
      +column_types:
        id: integer
        order_id: integer
        payment_method: string
        amount: number
